### ISSUE TITLE
Field order and Framebased set incorrectly

### ISSUE THREAD

**Issue by flossy83** [vapoursynth/bestsource#47]
As reported [here](https://forum.doom9.org/showthread.php?p=2000802#post2000802) there appears to be an issue with BSVideoSource setting the Avisynth clip properties:

1. Field order of the clip (result of clip.GetParity) 
2. Whether the clip is field based (result of clip.isFieldBased)  

To be clear these are in relation to clip properties not frame properties.

Thanks

**Comment by myrsloik** [comment]
I've changed #2 because that one is obvious. However let me point out that other source filters don't have a static value for GetParity (I mean what's the point of taking frame number as an argument if it has to be static?).

For example this code here definitely isn't constant:
https://github.com/HomeOfAviSynthPlusEvolution/L-SMASH-Works/blob/master/AviSynth/lwlibav_source.cpp#L249

I know there are bad clips with field order reversals out there so it can definitely change. Get me a sample of the problem clip and maybe I can figure out why it displeases you.

**Comment by flossy83** [comment]
Ok thanks, in that case I can workaround it with:

```
if (GetParity(0)){ AssumeTFF() }
else { AssumeBFF() }
```

As long as you are aware that without the above workaround it may create problems downstream compared to the other source filters - here's an example showing how it affects Bob()

```
file = https://drive.google.com/uc?export=download&id=1xz_WEX36iv8tpC18zR8e8-etGwtqfuVb

top_left = BSVideoSource(file, rff=true)
\ .Text("BSVideoSource\n_____________", align=5, lsp=0, size=30).Bob().info().Prefetch(1)

top_right = LWLibavVideoSource(file, repeat=true)
\ .Text("LWLibavVideoSource\n__________________", align=5, lsp=0, size=30).Bob().info().Prefetch(1)

bottom_left = FFVideoSource(file, rffmode=1)
\ .Text("FFVideoSource\n_____________", align=5, lsp=0, size=30).Bob().info().Prefetch(1)

bottom_right = DGSource(file, fieldop=0)
\.Text("DGSource\n________", align=5, lsp=0, size=30).Bob().info().Prefetch(1)

StackVertical(
\ StackHorizontal(top_left, top_right),
\ StackHorizontal(bottom_left, bottom_right))
```

The bobbed output is different with BS due to Bob obeying Avisynth internal field order which BS is setting differently per frame 

![debug avs_snapshot_00 04 938](https://github.com/vapoursynth/bestsource/assets/46382337/42279057-f703-40d2-a927-e9d1484d7e6f)

Rendered to x264 @ 60fps with ffmpeg.exe: https://drive.google.com/uc?export=download&id=14ohEANdh2S1czhuEnvbmgx01K8zJfI2N

**Comment by myrsloik** [comment]
Definitely different output but bobbing telecined material is in itself the definition of insanity. So closing this.
