### ISSUE TITLE
Warning: No entry point found in /usr/lib/vapoursynth/libbestsource.so

### ISSUE THREAD

**Issue by amayra** [vapoursynth/bestsource#57]
this error keeps showing up in both encoding and VapourSynth-Editor

the funny part is that it shows up even when I use FFMS2 as a source

**Comment by HolyWu** [comment]
It's in the wrong directory. Did you manually copy the built library rather than execute `ninja -C build install`? [libbestsource](https://github.com/vapoursynth/bestsource/blob/ff911facd49bd4edca253e1fd6e3d140ba668366/meson.build#L72) and [bestsource](https://github.com/vapoursynth/bestsource/blob/ff911facd49bd4edca253e1fd6e3d140ba668366/meson.build#L105) would be installed to different directory.

**Comment by amayra** [comment]
> It's in the wrong directory. Did you manually copy the built library rather than execute `ninja -C build install`? [libbestsource](https://github.com/vapoursynth/bestsource/blob/ff911facd49bd4edca253e1fd6e3d140ba668366/meson.build#L72) and [bestsource](https://github.com/vapoursynth/bestsource/blob/ff911facd49bd4edca253e1fd6e3d140ba668366/meson.build#L105) would be installed to different directory.

i used officially repo package from arch

**Comment by HolyWu** [comment]
Report to the responsible maintainer then.

**Comment by amayra** [comment]
thanks. What i should include in my report exactly?

**Comment by HolyWu** [comment]
Tell the maintainer to remove `--libdir /usr/lib/vapoursynth` from their build script. Otherwise the API library would be incorrectly installed to plugin directory and got autoloaded.

**Comment by EvgenyKV** [comment]
I have the same issue, my software source:
https://archlinux.org/packages/extra/x86_64/vapoursynth-plugin-bestsource/

**Comment by alucryd** [comment]
@HolyWu You need to give the library a proper soname and version it if you expect people to install it in `/usr/lib` and have ldconfig be happy.
